version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    user: "postgres"
  front:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: django
    volumes:
      - ./app:/code
    ports:
      - "8080:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
    depends_on:
      - db

# volumes:
#   data:

# volumes:
#   my_back:
#     driver: local
#     driver_opts:
#         type: none
#         o: bind
#         device: /mnt/c/Users/suria/Desktop/ts/jtest/app
